# Generated by Django 5.1.2 on 2026-02-17 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0006_tbl_subcategory'),
        ('Guest', '0004_tbl_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_details', models.CharField(max_length=30)),
                ('product_price', models.CharField(max_length=30)),
                ('product_photo', models.FileField(upload_to='Assets/product/Photo/')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_seller')),
            ],
        ),
    ]
