# Generated by Django 5.2.8 on 2026-03-07 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_subcategory'),
        ('Guest', '0004_tbl_seller'),
        ('Seller', '0002_tbl_gallery_tbl_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_deliveryboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryboy_name', models.CharField(max_length=30)),
                ('deliveryboy_email', models.CharField(max_length=30)),
                ('deliveryboy_contact', models.CharField(max_length=30)),
                ('deliveryboy_address', models.CharField(max_length=30)),
                ('deliveryboy_photo', models.FileField(upload_to='Assets/Seller/Photo/')),
                ('deliveryboy_proof', models.FileField(upload_to='Assets/Seller/proof/')),
                ('deliveryboy_password', models.CharField(max_length=60)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_seller')),
            ],
        ),
    ]
