# Generated by Django 5.2.8 on 2026-03-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_tbl_deliveryboy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_deliveryboy',
            name='deliveryboy_status',
            field=models.IntegerField(default=0),
        ),
    ]
