# Generated by Django 5.1.2 on 2026-02-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=30)),
                ('seller_email', models.CharField(max_length=30)),
                ('seller_contact', models.CharField(max_length=30)),
                ('seller_address', models.CharField(max_length=30)),
                ('seller_photo', models.FileField(upload_to='Assets/Seller/Photo/')),
                ('seller_proof', models.FileField(upload_to='Assets/Seller/proof/')),
                ('seller_passsword', models.CharField(max_length=60)),
            ],
        ),
    ]
