# Generated by Django 5.1.2 on 2026-02-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_seller',
        ),
    ]
