# Generated by Django 5.2.12 on 2026-03-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_seller',
            name='seller_status',
            field=models.IntegerField(default=0),
        ),
    ]
