# Generated by Django 5.1.2 on 2026-02-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_booking',
            name='Seller_id',
        ),
    ]
