# Generated by Django 5.1.2 on 2026-03-03 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_seller'),
        ('User', '0002_remove_tbl_booking_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
    ]
