# Generated by Django 5.2.8 on 2026-03-07 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_tbl_deliveryboy'),
        ('User', '0005_tbl_complaint_seller_id_tbl_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_date', models.DateField(auto_now_add=True)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_booking')),
                ('deliveryboy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.tbl_deliveryboy')),
            ],
        ),
    ]
