# Generated by Django 5.2.12 on 2026-03-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_tbl_assign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_assign',
        ),
    ]
