# Generated by Django 5.2.12 on 2026-03-10 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_tbl_deliveryboy_deliveryboy_status'),
        ('User', '0007_delete_tbl_assign'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_date', models.DateField(auto_now_add=True)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_booking')),
                ('deliveryboy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.tbl_deliveryboy')),
            ],
        ),
    ]
